raise Errors.BuildError(self.producer.error) BuildError: Build failed  -> task in 'testprog' failed (exit status 1): 	{task 139751538513168: cxx test.cpp -> test.cpp.1.o} ['g++', '-g', '-DNS3_LOG_ENABLE', '-DNS3_ASSERT_ENABLE', '-DHAVE_NS3_CORE=1', '-DHAVE_NS3_NETWORK=1', '-DHAVE_NS3_INTERNET=1', '-DHAVE_NS3_POINT_TO_POINT=1', '-DHAVE_NS3_MPI=1', '-DHAVE_STDINT_H=1', '-DHAVE_INTTYPES_H=1', '-DHAVE_SYS_TYPES_H=1', '-DHAVE_SYS_STAT_H=1', '-DHAVE_DIRENT_H=1', '-DHAVE_GETCPUFEATURES=1', '../test.cpp', '-c', '-o', 'test.cpp.1.o'] Added DCE mandatory modules to ns3 by default
DCE still fails though because of a failed checked dependancy

not found
from /home/teto/scratch/dce: The configuration failed
---------------------------------------------
Checking for header valgrind/memcheck.h
==>

int main() {
	return 0;
}

<==
[1/2] cxx: build/.conf_check_11b7b2c74b84e93c63133ee18ef65566/test.cpp -> build/.conf_check_11b7b2c74b84e93c63133ee18ef65566/testbuild/test.cpp.1.o

['g++', '-g', '-DNS3_LOG_ENABLE', '-DNS3_ASSERT_ENABLE', '-DHAVE_NS3_CORE=1', '-DHAVE_NS3_NETWORK=1', '-DHAVE_NS3_INTERNET=1', '-DHAVE_NS3_POINT_TO_POINT=1', '-DHAVE_NS3_MPI=1', '-DHAVE_STDINT_H=1', '-DHAVE_INTTYPES_H=1', '-DHAVE_SYS_TYPES_H=1', '-DHAVE_SYS_STAT_H=1', '-DHAVE_DIRENT_H=1', '-DHAVE_GETCPUFEATURES=1', '../test.cpp', '-c', '-o', 'test.cpp.1.o']
err: ../test.cpp:1:31: erreur fatale : valgrind/memcheck.h : No such file or directory
 #include <valgrind/memcheck.h>
                               ^
compilation terminée.

from /home/teto/scratch/dce: Test does not build: Traceback (most recent call last):
  File "/home/teto/scratch/dce/.waf-1.6.11-30618c54883417962c38f5d395f83584/waflib/Tools/c_config.py", line 445, in run_c_code
    bld.compile()
  File "/home/teto/scratch/dce/.waf-1.6.11-30618c54883417962c38f5d395f83584/waflib/Build.py", line 190, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed (exit status 1):
	{task 139751538458960: cxx test.cpp -> test.cpp.1.o}
['g++', '-g', '-DNS3_LOG_ENABLE', '-DNS3_ASSERT_ENABLE', '-DHAVE_NS3_CORE=1', '-DHAVE_NS3_NETWORK=1', '-DHAVE_NS3_INTERNET=1', '-DHAVE_NS3_POINT_TO_POINT=1', '-DHAVE_NS3_MPI=1', '-DHAVE_STDINT_H=1', '-DHAVE_INTTYPES_H=1', '-DHAVE_SYS_TYPES_H=1', '-DHAVE_SYS_STAT_H=1', '-DHAVE_DIRENT_H=1', '-DHAVE_GETCPUFEATURES=1', '../test.cpp', '-c', '-o', 'test.cpp.1.o']

not found
from /home/teto/scratch/dce: The configuration failed
---------------------------------------------
Checking for ns3-fd-net-device (None)
['/nix/store/1ccr6a50qadpgr1aa2c3a1rpylkzhzab-pkg-config-0.29.2/bin/pkg-config', 'None', '--cflags', '--libs']
err: Package None was not found in the pkg-config search path.
Perhaps you should add the directory containing `None.pc'
to the PKG_CONFIG_PATH environment variable
No package 'None' found

not found
from /home/teto/scratch/dce/myscripts/dce-emu-ping: The configuration failed

['g++', '-g', '-DNS3_LOG_ENABLE', '-DNS3_ASSERT_ENABLE', '-DHAVE_NS3_CORE=1', '-DHAVE_NS3_NETWORK=1', '-DHAVE_NS3_INTERNET=1', '-DHAVE_NS3_POINT_TO_POINT=1', '-DHAVE_NS3_MPI=1', '-DHAVE_STDINT_H=1', '-DHAVE_INTTYPES_H=1', '-DHAVE_SYS_TYPES_H=1', '-DHAVE_SYS_STAT_H=1', '-DHAVE_DIRENT_H=1', '-DHAVE_GETCPUFEATURES=1', '../test.cpp', '-c', '-o', 'test.cpp.1.o']
err: ../test.cpp:1:31: erreur fatale : valgrind/memcheck.h : No such file or directory
 #include <valgrind/memcheck.h>
                               ^
compilation terminée.