Added devShell for vimPluginsUpdater + changed path to wallpaper
add llama-cpp and rocks.nvim

reenable tailscale

opengl -> graphics + bumped nix to 2_23

adding serpl/kanpyo

fixing build of desktop

several fixes

updated CI

fixing secrets for calendar

fixing withSecrets

fixing withSecrets

trying to make the secretless nixosConfigurations more barebone

hopefully it has updated the bootloader ?

fixing bootloader |?

fix build

using rocsk more

starting to use teto/scratch version of rocks.nvim

fix rocks-config.nvim + nix

popcorn

adding neorg via rocks.nvim
moved some plugins to rocks.toml

keep sqlite in extraLuaPackages until smart-open is converted to
luarocks

fixed rest.nvim install via rocks.nvim
adding hurl + jujutsu config

removed gnome prefixes after a nixpkgs change

had to disable local-ai because fails to compile:
       > # github.com/mudler/LocalAI/backend/go/llm/bert
       > /nix/store/3v17dij8rvg7q99009swxg52995r7s22-go-1.22.5/share/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
       > /nix/store/2p1sq1nr09xr3xb1a9lrjgdanvk1aakb-binutils-2.42/bin/ld: cannot find -lcudart: No such file or directory
       > /nix/store/2p1sq1nr09xr3xb1a9lrjgdanvk1aakb-binutils-2.42/bin/ld: cannot find -lcudart: No such file or directory
       > /nix/store/2p1sq1nr09xr3xb1a9lrjgdanvk1aakb-binutils-2.42/bin/ld: cannot find -lcudart: No such file or directory
       > /nix/store/2p1sq1nr09xr3xb1a9lrjgdanvk1aakb-binutils-2.42/bin/ld: cannot find -lcudart: No such file or directory
       > collect2: error: ld returned 1 exit status
       >
       > make: *** [Makefile:663: backend-assets/grpc/bert-embeddings] Error 1
       For full logs, run 'nix log /nix/store/3z4ap2b1c0vfj19q0mnyli1gjahpdgg8-local-ai-2.18.1.drv'.
error: 1 dependencies of derivation '/nix/store/bf29i8vs7bzh4avdlq76qgm4fks5cp9g-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/611hypg31wmgi71vd5nlv40157zywr5w-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l9nfxbyg7l320b0rgcjy38q1vqg9dac4-user-environment.drv' failed to build

removed lazy + handle mpv config manually

solved smart-open locally

bumped flake

add meli

moving sops to home-manager level

+ some gp.nvim setup

adding home manager modules

formatted all files

adding baleai + automated bin/luarocks

fixed firefox config

fixing